"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import { CacheProvider } from '@chakra-ui/next-js'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
            <CacheProvider>
              <ChakraProvider>
                <Navbar />
                  {children}
               <Footer />
              </ChakraProvider>
            </CacheProvider>
      </body>
    </html>
  )
}
